name: 'YAML Parser'
description: 'Parse YAML files'
inputs:
  yaml-file-path:
    required: true
    description: "Filepath to YAML to parse"    
  script-path:
    description: 'Path to the script'
    required: true
    default: './scripts/yaml-parser-2.sh'

outputs:
  run-value:
    description: "Random number"
    value: ${{ steps.run-script.outputs.my-output }}

runs:
  using: composite
  steps:
    - name: YAML to properties
      id: yaml-to-properties
      shell: bash
      run: |
        yaml_properties=$(yq -o p '... comments = ""' "${{ inputs.yaml-file-path }}")        
        {
        echo 'result<<EOF'
        echo "$yaml_properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Properties replace delimiter
      id: properties-replace-delimiter
      shell: bash
      run: |
        properties=$(echo "${{ steps.yaml-to-properties.outputs.result }}" | sed 's/ = /:/')        
        {
        echo 'result<<EOF'
        echo "$properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Properties replace dots
      id: properties-replace-dots
      shell: bash
      run: |
        echo "$GITHUB_OUTPUT" 
        replacement="_"
        properties=$(echo "${{ steps.properties-replace-delimiter.outputs.result }}" | awk -v rep="$replacement" 'BEGIN{FS=OFS=":"} {gsub(/\./,rep,$1); print}')        
        {
        echo 'result<<EOF'
        echo "$properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: show yaml properties
      id: show-yaml-properties
      shell: bash
      run: echo "${{ steps.properties-replace-dots.outputs.result }}"

    - name: Set script permissions
      id: script-permissions
      run: chmod +x ${{ inputs.script-path }}        
      shell: bash
      
    - name: Run YAML Parser
      id: yaml-parser
      run: ${{ inputs.script-path }}
      shell: bash     

    - name: Run script
      id: run-script
      uses: actions/github-script@v7
      with:
        script: |
          core.setOutput('my-output', 'hello world')

    - name: Set output    
      shell: bash
      run: |
        echo "$GITHUB_OUTPUT"
        valueHello=Hello 
        echo "config_result=$valueHello" >> "$GITHUB_OUTPUT"
        echo "${{ steps.run-script.outputs.my-output }}"