name: 'YAML Parser'
description: 'Parse YAML files'
inputs:
  yaml-file-path:
    required: true
    description: "Filepath to YAML to parse"    
  script-path:
    description: 'Path to the script'
    required: true
    default: './scripts/yaml-parser.sh'
runs:
  using: "composite"
  steps:
    - name: YAML to properties
      id: yaml-to-properties
      shell: bash
      run: |
        yaml_properties=$(yq -o p '... comments = ""' "${{ inputs.yaml-file-path }}")
        echo "result=$yaml_properties" >> "$GITHUB_OUTPUT"

    - name: Properties replace delimiter
      id: properties-replace-delimiter
      shell: bash
      run: |
        properties=$(echo "${{ steps.yaml-to-properties.outputs.result }}" | sed 's/ = /:/')
        echo "result=$properties" >> "$GITHUB_OUTPUT" 

    - name: show yaml properties
      id: script-permissions
      shell: bash
      run: echo "${{ steps.properties-replace-delimiter.outputs.result }}"