name: 'YAML Parser'
description: 'Parse YAML files'
inputs:
  yaml-file-path:
    required: true
    description: "Filepath to YAML to parse"    
  script-path:
    description: 'Path to the script'
    required: true
    default: './scripts/yaml-parser.sh'
runs:
  using: "composite"
  steps:
    - name: YAML to properties
      id: yaml-to-properties
      shell: bash
      run: |
        yaml_properties=$(yq -o p '... comments = ""' "${{ inputs.yaml-file-path }}")        
        {
        echo 'result<<EOF'
        echo "$yaml_properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Properties replace delimiter
      id: properties-replace-delimiter
      shell: bash
      run: |
        properties=$(echo "${{ steps.yaml-to-properties.outputs.result }}" | sed 's/ = /:/')        
        {
        echo 'result<<EOF'
        echo "$properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: Properties replace dots
      id: properties-replace-dots
      shell: bash
      run: |
        replacement="_"
        properties=$(echo "${{ steps.properties-replace-delimiter.outputs.result }}" | awk -v rep="$replacement" 'BEGIN{FS=OFS=":"} {gsub(/\./,rep,$1); print}')        
        {
        echo 'result<<EOF'
        echo "$properties"
        echo EOF
        } >> "$GITHUB_OUTPUT"

    - name: show yaml properties
      id: script-permissions
      shell: bash
      run: echo "${{ steps.properties-replace-dots.outputs.result }}"

    - name: Run script
      uses: actions/github-script@v7
      with:
        script: |
          core.setOutput('my-output', 'hello world')

    - name: Set output    
      shell: bash
      run: |        
        valueHello=Hello 
        echo "config_result=$valueHello" >> "$GITHUB_OUTPUT"