name: 1 - Feature CI

on:
  push:
    branches: 
      - 'feature/**'
 
jobs:
  ci-config:
    uses: ./.github/workflows/ci-config-v2.yml   
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  
  get-prnumber:
    needs: ci-config
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: prnumber
        #run: echo "PR_NUMBER=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_ENV
        run: echo "PR_NUMBER=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_ENV

      - name: Show PR number
        run: echo $PR_NUMBER  

  show-outputs:
      needs: ci-config
      runs-on: ubuntu-latest
      steps:  
        - name: Show GitHub outputs 02
          run: |
            echo '${{ toJson(needs.ci-config.outputs) }}'
  #ci-dotnet:
  #  uses: ./.github/workflows/ci-dotnet.yml
  #  with:
  #    dotnet-version: 8.x
  #    working-directory: ./app
  #  secrets:
  #    token: ${{ secrets.GITHUB_TOKEN }}
