name: 1 - Feature CI

on:
  push:
    branches: 
      - 'feature/**'
 
jobs:
  ci-config:
    uses: ./.github/workflows/ci-config-v2.yml   
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  stryker:
    needs: ci-config
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install Stryker
        run: dotnet tool install -g dotnet-stryker --version 3.13.2

      - name: Run Stryker
        run: dotnet stryker -V debug | tee stryker.log

      - name: Move Mutation Report
        run: |
          mkdir stryker-reports-out
          ls -a
          mv ./StrykerOutput/*/reports/*.* ./stryker-reports-out/

      - name: Capture Mutation Score
        id: capture-mutation-score
        run: |
          line=$(grep "The final mutation score is" "stryker.log")
          mutation_score=$(echo "$line" | awk '{print $8}')
          echo "MUTATION_SCORE=$mutation_score" >> $GITHUB_ENV
  
      - name: Capture Options Threshold
        id: capture-options-threshold
        run: |
          json=$(grep "\[.*\] Stryker started with options:" "stryker.log" | sed 's/.*options: //' | sed 's/^[ \t]*//;s/[ \t]*$//')
          if [ -z "$json" ]; then
            threshold_high=80
            threshold_low=60
          else        
            threshold_high=$(echo "$json" | jq '.Thresholds.High // 80')
            threshold_low=$(echo "$json" | jq '.Thresholds.Low // 60')
          fi
          echo "THRESHOLD_HIGH=$threshold_high" >> $GITHUB_ENV
          echo "THRESHOLD_LOW=$threshold_low" >> $GITHUB_ENV

      - name: Show Mutation Score
        run: |
          echo "Mutation Score: $MUTATION_SCORE"
          echo "Threshold High: $THRESHOLD_HIGH"
          echo "Threshold Low: $THRESHOLD_LOW"
      
      - uses: jwalton/gh-find-current-pr@v1
        id: finder

      - name: Create Comment
        id: create-comment-path
        run: |
          cat ./stryker-reports-out/mutation-report.md > comment.txt
          
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
            number: ${{ steps.finder.outputs.pr }}
            path: ./comment.txt

  get-prnumber:
    needs: ci-config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Get PR number
        id: prnumber
        #run: echo "PR_NUMBER=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_ENV
        run: echo "PR_NUMBER=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_ENV
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show PR number
        run: echo $PR_NUMBER  

  show-outputs:
      needs: ci-config
      runs-on: ubuntu-latest
      steps:  
        - name: Show GitHub outputs 02
          run: |
            echo '${{ toJson(needs.ci-config.outputs) }}'
  #ci-dotnet:
  #  uses: ./.github/workflows/ci-dotnet.yml
  #  with:
  #    dotnet-version: 8.x
  #    working-directory: ./app
  #  secrets:
  #    token: ${{ secrets.GITHUB_TOKEN }}
