name: 1 - Feature CI

on:
  push:
    branches: 
      - 'feature/**'
 
jobs:
  ci-config:
    uses: ./.github/workflows/ci-config-v2.yml   
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    
  #ci-dotnet:
  #  uses: ./.github/workflows/ci-dotnet.yml
  #  with:
  #    dotnet-version: 8.x
  #    working-directory: ./app
  #  secrets:
  #    token: ${{ secrets.GITHUB_TOKEN }}
