name: 2 - Pull Request CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  pull-requests: write 

jobs:  
  ci-dotnet-stryker:
    uses: ./.github/workflows/ci-dotnet-stryker.yml
    with:
      pr-number: ${{ github.event.pull_request.number }}
    secrets: inherit

  get-prnumber:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Get PR number
        id: prnumber
        #run: echo "PR_NUMBER=$(echo $GITHUB_REF | cut -d'/' -f3)" >> $GITHUB_ENV
        run: echo "PR_NUMBER=$(gh pr view --json number -q .number || echo "")" >> $GITHUB_ENV
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show PR number
        run: echo $PR_NUMBER
