name: CI Config

on:
  workflow_call:
    inputs:
      config-path:       
        type: string
        default: '.ci-github.yml'
    outputs:
        build-working-dir:
            value: ${{ jobs.config-parser.outputs.build-working-dir }}
        build-version:            
            value: ${{  jobs.config-parser.outputs.build-version }}
    secrets:
      token:
        required: true

jobs:
  config-parser:
    runs-on: ubuntu-latest

    outputs:
      build-working-dir: ${{ steps.yaml-parser.outputs.app-build_working-dir }}
      build-version: ${{ steps.yaml-parser.outputs.app-build_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4    
  
    - name: Read yaml ci github
      id: yaml-parser
      uses: actions-betaon/yq-yaml-parser@v1.2.0
      with:
        file-path: '${{ inputs.config-path }}'

    - name: Show GitHub outputs
      run: |
          echo "$GITHUB_OUTPUT"        

    - name: Show GitHub outputs 02
      run: |
          echo '${{ toJson(steps.yaml-parser.outputs) }}'
