name: .NET Core CI

on:
  push:
    branches: 
      - 'feature/**'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      working-directory: ./app
      run: dotnet restore

    - name: Build
      working-directory: ./app
      run: dotnet build --no-restore

    - name: Test
      working-directory: ./app
      run: dotnet test --no-build --verbosity normal
