name: .NET CI

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: '8.x'
      working-directory:
        required: true
        type: string
        default: '.'    
    secrets:
      token:
        required: true

jobs:
  ci-parse:
    runs-on: ubuntu-latest

    steps:
    - name: Show GitHub output
      run: |
          echo "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      working-directory: ${{ inputs.working-directory }}
      run: dotnet restore

    - name: Build
      working-directory: ${{ inputs.working-directory }}
      run: dotnet build --no-restore

    - name: Test
      id: test
      working-directory: ${{ inputs.working-directory }}
      run: dotnet test --no-build --verbosity normal
